name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore NuGet packages
      run: msbuild -t:restore

    - name: Build
      run: msbuild -p:Configuration=Release

    - name: Test
      run: |
        # Aquí debes poner el comando para ejecutar tus pruebas unitarias
        echo "Ejecutando pruebas..."

    - name: SonarQube Scan
      uses: sonarsource/sonar-scanner-msbuild-action@v1.1
      with:
        serverUrl: ${{ secrets.SONAR_HOST_URL }}
        login: ${{ secrets.SONAR_TOKEN }}
