name: CI

on:
  push:
    branches: [ main, CI ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore NuGet packages
      run: msbuild -t:restore

    - name: Build
      run: msbuild -p:Configuration=Release

    - name: Test
      run: |
        # Aquí debes poner el comando para ejecutar tus pruebas unitarias
        echo "Ejecutando pruebas..."

    - name: OWASP Dependency Check
      uses: dependency-check/DependencyCheck_Action@v2
      with:
        scanPath: '.'
        format: 'ALL'
        failBuildOnCVSS: '7'
        suppressionPath: 'dependency-check-suppression.xml'

    - name: Lint with StyleCop
      run: dotnet build --configuration Release

    - name: Comment on PR
      uses: actions/github-script@v3
      with:
        script: |
          github.issues.createComment({
            issue_number: context.pullRequest.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '🎉 Your CI tests passed!'
          })
        github-token: ${{ secrets.GITHUB_TOKEN }}
